name: Update Bitcoin Sheet

on:
  schedule:
    - cron: '0 6 * * *'   # 06:00 UTC (09:00 по Молдове)
    - cron: '0 15 * * *'  # 15:00 UTC (18:00 по Молдове)
  workflow_dispatch:       # Ручной запуск

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client requests beautifulsoup4 pytz google-api-python-client google-auth

      - name: Write credentials.json
        run: |
          printf '%s' "$GOOGLE_CREDENTIALS" > credentials.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Run update script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python update_sheet.py
